### ISSUE TITLE
API valutazione scuola trentina

### ISSUE THREAD

**Issue by napo** [DigitalCommonsLab/osm4schools#19]
**Informazioni base sulle scuole**<br/>
https://aprilascuola.provincia.tn.it/sei//api/istituzioneScolastica/istituzioni/{idscuolaprovincia}

{idscuolaprovincia} = corrisponde all'identificativo unico della scuola secondo gli id dati dalla Provincia Autonome di Trento.

Es.<br/>
idscuolaprovincia = 0222057111<br/>
https://aprilascuola.provincia.tn.it/sei//api/istituzioneScolastica/istituzioni/0222057111

**Informazioni su statistiche studenti di una scuola**

https://aprilascuola.provincia.tn.it/sei//api/istituzioneScolastica/istituzioni/{idscuolaprovincia}/alunni

Es.<br/>
idscuolaprovincia = 0222057111<br/>
https://aprilascuola.provincia.tn.it/sei//api/istituzioneScolastica/istituzioni/0222057111

**Comment by napo** [comment]
Esiste anche

- https://aprilascuola.provincia.tn.it/sei//api/istituzioneScolastica/istituzioni/ricerca => restituisce **tutte** le scuole
- https://aprilascuola.provincia.tn.it/sei//api/istituzioneScolastica/comuni => codici di tutti **comuni**
- https://aprilascuola.provincia.tn.it/sei//api/istituzioneScolastica/comunitaDiValle => codici di tutte le *comunità di valle**
- https://aprilascuola.provincia.tn.it/sei//api/istituzioneScolastica/tipiIstituzione => restituisce l'elenco dei **tipi di istruzione**

**Comment by stefanocudini** [comment]
@napo  sono riuscito a includere il supporto a c3js e mantenere il funzionamento del radar(che non e' incluso in c3) per cui ora possiamo supportare ogni grafico che sia costruibile con c3:
https://c3js.org/examples.html#chart
