### ISSUE TITLE
charts:  barre orizzontali: stacked 5x5 - barre verticali stacked 2x2

### ISSUE THREAD

**Issue by stefanocudini** [DigitalCommonsLab/osm4schools#6]

**Comment by napo** [comment]
![barre orizzontali stacked 5x5](https://user-images.githubusercontent.com/69814/39749128-342987c2-52b2-11e8-98f2-f3a6db173086.png)
![barre orizzontali stacked 2x2](https://user-images.githubusercontent.com/69814/39749131-363cc0e2-52b2-11e8-9af2-3cc0e70c0d78.png)
