### ISSUE TITLE
charts: radar su 7 variabili

### ISSUE THREAD

**Issue by stefanocudini** [DigitalCommonsLab/osm4schools#7]
selezione scuole per ogni punto sul radar

**Comment by napo** [comment]
![selection_134](https://user-images.githubusercontent.com/69814/39750971-fb2550d2-52b6-11e8-989a-56075cd11f81.png)
sorca
http://bl.ocks.org/nbremer/21746a9668ffdf6d8242

**Comment by stefanocudini** [comment]
l'originale "spigoloso" su github da cui e' stata fatta le version smooth
https://github.com/alangrafu/radar-chart-d3

**Comment by napo** [comment]
# Layer:
- un layer potrebbe essere quello della media nazionale quindi, per ora, facciamo tutto a 4,5
- un secondo layer è quello della scuola

## In futuro:
- layer della Provincia? Comune? Regione?
- layer nazionale
- layer scuola


# codici

I codici sono divisi fra ESITI  (codici 21-24) e PROCESSI (31-37)

Sorgente dati: http://dati.istruzione.it/opendata/opendata/catalogo/elements1/RUBRICA_VAL20161720170831.csv

|CODICECRITERIOQUALITA|CRITERIOQUALITA|
----------------------------------------|-----------------------------
|21|Risultati scolastici|
|22|Risultati nelle prove standardizzate nazionali|
|23|Competenze chiave europee|
|24|Risultati a distanza|     
|31|Curricolo, progettazione e valutazione|
|32|Ambiente di apprendimento|
|33|Inclusione e differenziazione|
|34|Continuita' e orientamento|
|35|Orientamento strategico e organizzazione della scuola|
|36|Sviluppo e valorizzazione delle risorse umane|
|37|Integrazione con il territorio e rapporti con le famiglie|

# range valori 
da 1 a 7 in float


# testo da inserire
---
# Punteggio di Riferimento

Valore utilizzato dall'istituto per l'assegnazione del punteggio per i criteri di valutazione. 

I valori sono compresi tra *1* e *7* e vengono indicati *1*, *3*, *5* e *7*; i valori 2, 4 e 6 _non_ sono esplicitati e permettono di posizionare le scuole che riscontrano una corrispondenza tra la descrizione e la situazione effettiva solo in relazione ad alcuni aspetti. 

    1 = situazione molto critica; 
    
    3 = situazione con qualche criticità;
    
    5 = situazione positiva;
    
    7 = situazione eccellente

**Comment by stefanocudini** [comment]
moved to new issue #14
