### ISSUE TITLE
query overpass per amenity=school

### ISSUE THREAD

**Issue by napo** [DigitalCommonsLab/osm4schools#8]
- considerare solo le scuole con name e https://wiki.openstreetmap.org/wiki/Key:isced:level
- al clic mostrare name, operator (se c'è), isced:level (secondo wiki) e website (se c'è) ...

**Comment by stefanocudini** [comment]
dati osm gia scaricati:
https://drive.google.com/drive/folders/1OTazA8OZXu0IJbIyyWjAjUMK8j4uXbgZ
